name: UVX Lint

on:
  pull_request:
    paths:
      - "backend/**"
    branches:
      - "dev"
      - "main"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/ruff-action@v2
        with:
          src: "./backend"
      - run: ruff check backend/
