name: Prettier Formatting

on:
  pull_request:
    branches:
      - main
      - dev
    paths:
      - "frontend/**"

jobs:
  prettier:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.base.ref }}

      - name: Install dependencies
        run: yarn install
        working-directory: frontend/

      - name: Prettify code
        uses: creyD/prettier_action@v4.3
        with:
          prettier_options: --write **/*.{js,ts,tsx,json,md,css}

      - name: Commit and push Prettier fixes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "chore: Fix Prettier issues" || echo "No changes to commit"
          git push
